#!/usr/bin/env python3
"""
Retrieves all documents from the 'school' collection
where the 'name' field starts with 'Holberton'.
"""

from pymongo import MongoClient
import sys

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 list_holberton_schools.py <database_name>")
        sys.exit(1)

    database_name = sys.argv[1]
    client = MongoClient()
    db = client[database_name]
    schools = db.school.find({"name": {"$regex": "^Holberton"}})

    for school in schools:
        print(school)
